### ISSUE TITLE
Create 'people profiles' in the data templates

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#44]
See https://github.com/pharmaverse/pharmaverse/issues/7

Once we have that, can also add normal profile pages, or do a second page that has the profiles in cards.

**Comment by epijim** [comment]
Idea (starting in branch `issue44`):

## Data

Create a yaml per person using primary github handle.

```
data
-- people
    |- epijim.yaml
    |- rossfarrugia.yaml
```

In the yaml have (example `epijim.yaml`):

```yaml
# required
name: James Black
pharmaverse_roles: tech
company: Roche
company_logo: link to images folder (could make a lookup... but maybe not worth the effort)
# Following is more a nice to have for profile pages [and optional]
linkedin: https://www.linkedin.com/in/epijim/
site: https://epijim.uk
title: People and Product Family Leader for Insights Engineering, Scientific Computing Environment Product Owner
bio: James is currently leading our pan-study codebase for insights, across clinical trials and RWD. He joined Roche 6 years ago from grad-school, and in that time has worked across RWD, PHC and now in this engineering aligned role.
```

In the yaml have (example `rossfarrugia.yaml`):

```yaml
# required
name: Ross Farrugia
pharmaverse_roles: council, tech, data
[skipping the rest, as main point is we can edit the roles here]
```

Then we build the people info dynamically. And... can also build some people pages, enriching it with other data - e.g. which of the pharmaverse projects they contribute to (via the github metadata).
